### ISSUE TITLE
Create default import format for flatrate terms

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-dist-orgs#36]
based on https://github.com/metasfresh/metasfresh/issues/2224

**Comment by teosarca** [comment]
NOTE: in task https://github.com/metasfresh/metasfresh/issues/2224 i already provided a default import format. Pls pimp that one.

The format i've used is this one:
https://github.com/metasfresh/metasfresh/issues/2224#issuecomment-327152218
