### ISSUE TITLE
Have a direct relation between order and invoice candidate

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-dist-orgs#88]

**Comment by metas-ts** [comment]
hi @metasnw afaiu this is exacltyl what the issue #2905 is about.
pls check when it's rolled out

**Comment by metasnw** [comment]
@metas-ts ok, thx. will do

**Comment by metasnw** [comment]
@metas-ts I checked it out and I found the relation from order to invoice to be gone if you create flatrate terms. my test: https://w101.metasfresh.com:8443/window/143/1000062

if you dont want it in metasfresh we need to create it in dist-orgs

**Comment by metasnw** [comment]
solved via https://github.com/metasfresh/metasfresh/issues/3010
